services:
  - type: web
    name: securevalidator-auto
    rootDir: Buoi1/Lab1  # Sửa dòng này thành Buoi1/Lab1
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free